name: Seurat_conda
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - argcomplete=1.12.3
  - async-timeout=4.0.2
  - attrs=22.2.0
  - binutils_impl_linux-64=2.39
  - boto=2.49.0
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - crcmod=1.7
  - cromwell=0.40
  - cryptography=39.0.0
  - curl=7.87.0
  - expat=2.5.0
  - fasteners=0.17.3
  - findutils=4.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - gcc_impl_linux-64=12.2.0
  - gcs-oauth2-boto-plugin=3.0
  - geos=3.11.1
  - gettext=0.21.1
  - gfortran_impl_linux-64=12.2.0
  - glpk=5.0
  - gmp=6.2.1
  - google-apitools=0.5.32
  - google-auth=2.15.0
  - google-reauth=0.1.1
  - graphite2=1.3.13
  - gsl=2.7
  - gsutil=5.17
  - gxx_impl_linux-64=12.2.0
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - httplib2=0.20.4
  - icu=70.1
  - idna=3.4
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsanitizer=12.2.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - make=4.3
  - monotonic=1.5
  - multidict=6.0.4
  - ncurses=6.3
  - oauth2client=4.1.3
  - openjdk=8.0.332
  - openssl=3.0.7
  - pandoc=2.19.2
  - pango=1.50.12
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.0
  - python_abi=3.11
  - pyu2f=0.1.5
  - r-abind=1.4_5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.2.2
  - r-base64enc=0.1_3
  - r-bh=1.78.0_0
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.3
  - r-broom=1.0.2
  - r-bslib=0.4.2
  - r-cachem=1.0.6
  - r-callr=3.7.3
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-cli=3.6.0
  - r-clipr=0.8.0
  - r-cluster=2.1.4
  - r-codetools=0.2_18
  - r-colorspace=2.0_3
  - r-commonmark=1.8.1
  - r-cowplot=1.1.1
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-crosstalk=1.2.0
  - r-curl=4.3.3
  - r-data.table=1.14.6
  - r-dbi=1.1.3
  - r-dbplyr=2.2.1
  - r-deldir=1.0_6
  - r-digest=0.6.31
  - r-dplyr=1.0.10
  - r-dqrng=0.3.0
  - r-dtplyr=1.2.2
  - r-ellipsis=0.3.2
  - r-evaluate=0.19
  - r-fansi=1.0.3
  - r-farver=2.1.1
  - r-fastmap=1.1.0
  - r-fitdistrplus=1.1_8
  - r-fnn=1.1.3.1
  - r-fontawesome=0.4.0
  - r-forcats=0.5.2
  - r-fs=1.5.2
  - r-future=1.30.0
  - r-future.apply=1.10.0
  - r-gargle=1.2.1
  - r-generics=0.1.3
  - r-ggplot2=3.4.0
  - r-ggrepel=0.9.2
  - r-ggridges=0.5.4
  - r-globals=0.16.2
  - r-glue=1.6.2
  - r-goftest=1.2_3
  - r-googledrive=2.0.0
  - r-googlesheets4=1.0.1
  - r-gplots=3.1.3
  - r-gridextra=2.3
  - r-gtable=0.3.1
  - r-gtools=3.9.4
  - r-haven=2.5.1
  - r-hdf5r=1.3.7
  - r-here=1.0.1
  - r-hexbin=1.28.2
  - r-highr=0.10
  - r-hms=1.1.2
  - r-htmltools=0.5.4
  - r-htmlwidgets=1.6.1
  - r-httpuv=1.6.7
  - r-httr=1.4.4
  - r-ica=1.0_3
  - r-ids=1.0.1
  - r-igraph=1.3.5
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.4
  - r-kernsmooth=2.23_20
  - r-knitr=1.41
  - r-labeling=0.4.2
  - r-later=1.3.0
  - r-lattice=0.20_45
  - r-lazyeval=0.2.2
  - r-leiden=0.4.3
  - r-lifecycle=1.0.3
  - r-listenv=0.9.0
  - r-lmtest=0.9_40
  - r-lsei=1.3_0
  - r-lubridate=1.9.0
  - r-magrittr=2.0.3
  - r-mass=7.3_58.1
  - r-matrix=1.5_3
  - r-matrixstats=0.63.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_41
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-modelr=0.1.10
  - r-munsell=0.5.0
  - r-nlme=3.1_161
  - r-npsurv=0.5_0
  - r-openssl=2.0.5
  - r-parallelly=1.33.0
  - r-patchwork=1.1.2
  - r-pbapply=1.6_0
  - r-pillar=1.8.1
  - r-pkgconfig=2.0.3
  - r-plotly=4.10.1
  - r-plyr=1.8.8
  - r-png=0.1_8
  - r-polyclip=1.10_4
  - r-prettyunits=1.1.1
  - r-processx=3.8.0
  - r-progress=1.2.2
  - r-progressr=0.12.0
  - r-promises=1.2.0.1
  - r-ps=1.7.2
  - r-purrr=1.0.0
  - r-r6=2.5.1
  - r-rann=2.6.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.9
  - r-rcppannoy=0.0.20
  - r-rcpparmadillo=0.11.4.2.1
  - r-rcppeigen=0.3.3.9.3
  - r-rcppparallel=5.1.6
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.1.7
  - r-readr=2.1.3
  - r-readxl=1.4.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.2
  - r-reshape2=1.4.4
  - r-reticulate=1.25
  - r-rgeos=0.6_1
  - r-rlang=1.0.6
  - r-rmarkdown=2.19
  - r-rocr=1.0_11
  - r-rprojroot=2.0.3
  - r-rspectra=0.16_1
  - r-rstudioapi=0.14
  - r-rtsne=0.16
  - r-rvest=1.0.3
  - r-sass=0.4.4
  - r-scales=1.2.1
  - r-scattermore=0.8
  - r-sctransform=0.3.5
  - r-selectr=0.4_2
  - r-seurat=4.3.0
  - r-seuratobject=4.1.3
  - r-shiny=1.7.4
  - r-sitmo=2.0.2
  - r-sourcetools=0.1.7
  - r-sp=1.5_1
  - r-spatstat.data=3.0_0
  - r-spatstat.explore=3.0_5
  - r-spatstat.geom=3.0_3
  - r-spatstat.random=3.0_1
  - r-spatstat.sparse=3.0_0
  - r-spatstat.utils=3.0_1
  - r-stringi=1.7.8
  - r-stringr=1.5.0
  - r-survival=3.5_0
  - r-sys=3.4.1
  - r-tensor=1.5
  - r-tibble=3.1.8
  - r-tidyr=1.2.1
  - r-tidyselect=1.2.0
  - r-tidyverse=1.3.2
  - r-timechange=0.1.1
  - r-tinytex=0.43
  - r-tzdb=0.3.0
  - r-utf8=1.2.2
  - r-uuid=1.1_0
  - r-uwot=0.1.14
  - r-vctrs=0.5.1
  - r-viridislite=0.4.1
  - r-vroom=1.6.0
  - r-withr=2.5.0
  - r-xfun=0.36
  - r-xml2=1.3.3
  - r-xtable=1.8_4
  - r-yaml=2.3.6
  - r-zoo=1.8_11
  - readline=8.1.2
  - requests=2.28.1
  - retry_decorator=1.1.1
  - rsa=4.9
  - sed=4.8
  - setuptools=65.6.3
  - six=1.16.0
  - socksipy-branch=1.01
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.38.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yarl=1.8.2
  - zlib=1.2.13
  - zstd=1.5.2
